title: Avry Jackson
description: Documentation for my project
# logo: "unamed.png"  # optional logo
theme: just-the-docs
color_scheme: "dark"

url: https://just-the-docs.github.io

aux_links:
  My Github Profile: https://github.com/avryjacksoncom

nav:
  - title: "Projects"
    url: /projects
